spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Travel Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      travelbank:
        gatewayserver: DEBUG
        
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
#below for error we need time dely or backend and gateway...nothing but overridign the circuit breaker timeout.
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        slidingWindowSize: 10
#        permittedNumberOfCallsInHalfOpenState: 2
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#  timelimiter:
#    configs:
#      default:
#        timeoutDuration: 10s 

